name: Python application

on:
  pull_request:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        docker login --username=dockerc721 --password=${{ secrets.DOCKERPASSWD }}
        docker image build -t dockerc721/gitops:hellov1.0.2 .
        docker push dockerc721/gitops:hellov1.0.2
